name: Docker Build and Push

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1  # Update this to your desired region

    - name: Build Docker Image
      run: docker build -t ghost-app .

    - name: Log into Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 195678812469.dkr.ecr.eu-west-1.amazonaws.com

    - name: Tag Docker Image
      run: docker tag ghost-app:latest 195678812469.dkr.ecr.eu-west-1.amazonaws.com/ghost-app:latest

    - name: Push Docker Image to ECR
      run: docker push 195678812469.dkr.ecr.eu-west-1.amazonaws.com/ghost-app:latest
